services:

  db_dev:
    image: postgres
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DATABASE: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ncfca-db-dev-data:/var/lib/mysql
    networks:
      - ncfca-net
  
  rabbitmq:
    image: rabbitmq:4.1.2-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/

volumes:
  ncfca-db-dev-data:
  ncfca-db-test-data:    
  rabbitmq_data:
networks:
  ncfca-net:
    driver: bridge
