
export const TOURNAMENT_EVENTS_SERVICE = Symbol('TOURNAMENT_EVENTS_SERVICE');
export const EVENT_EMITTER_FACADE = Symbol('EVENT_EMITTER_FACADE');
export const CLUB_EVENTS_SERVICE = Symbol('CLUB_EVENTS_SERVICE');
export const TOURNAMENT_EMITTER = Symbol('TOURNAMENT_EMITTER');
export const CLUB_EMITTER = Symbol('CLUB_EMITTER');
