export const TRANSACTION_REPOSITORY = Symbol('TRANSACTION_REPOSITORY');
export const FAMILY_REPOSITORY = Symbol('FAMILY_REPOSITORY');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const CLUB_REPOSITORY = Symbol('CLUB_REPOSITORY');
export const CLUB_REQUEST_REPOSITORY = Symbol('CLUB_REQUEST_REPOSITORY');
